version: "3.9"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    environment:
      JVMFLAGS: "-Xmx1024m -Xms1024m"
    ports:
      - "2181:2181"
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1024M
    ulimits:
      nproc: 65535
      nofile:
        soft: 100000
        hard: 100000

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_CREATE_TOPICS: "test-topic:1:1"
    depends_on:
      - zookeeper
    deploy:
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 2048M
    ulimits:
      nproc: 65535
      nofile:
        soft: 100000
        hard: 100000

networks:
  default:
    driver: bridge
    name: kafka_rust_network
